import{a as p,i,S as g}from"./assets/vendor-DUVIkWpV.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const L="45565768-ade7924c670b62e50b9d023f8",w="https://pixabay.com/api/";async function f(s,t=1,a=15){return(await p.get(w,{params:{key:L,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:a}})).data}function h(s){return s.map(({webformatURL:t,largeImageURL:a,tags:o,likes:e,views:r,comments:n,downloads:y})=>`
        <li class="gallery-item">
          <a class="a-img" href="${a}">
            <img class="gallery-img" src="${t}" alt="${o}" loading="lazy" />
          </a>
          <div class="info">
            <p class="p-likes" >Likes ${e}</p>
            <p class="p-views" >Views ${r}</p>
            <p class="p-comments" >Comments ${n}</p>
            <p class="p-downloads" >Downloads ${y}</p>
          </div>
        </li>`).join("")}const b=document.querySelector("#search-form"),m=document.querySelector(".gallery"),c=document.querySelector("#load-more"),d=document.querySelector("#loader");let l="",u=1;b.addEventListener("submit",S);c.addEventListener("click",v);async function S(s){if(s.preventDefault(),l=s.currentTarget.elements.query.value.trim(),!l){i.error({title:"Error",message:"Search query cannot be empty"});return}try{d.classList.remove("hidden"),m.innerHTML="",u=1;const{hits:t,totalHits:a}=await f(l,u);if(t.length===0){i.warning({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"}),c.classList.add("hidden");return}m.innerHTML=h(t),new g(".gallery a").refresh(),t.length<a&&c.classList.remove("hidden")}catch{i.error({title:"Error",message:"Something went wrong, please try again later"})}finally{d.classList.add("hidden")}}async function v(){u+=1;try{d.classList.remove("hidden");const{hits:s,totalHits:t}=await f(l,u);m.insertAdjacentHTML("beforeend",h(s)),new g(".gallery a").refresh();const o=document.querySelectorAll(".gallery-item"),e=o[0].getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"}),o.length>=t&&(c.classList.add("hidden"),i.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."}))}catch{i.error({title:"Error",message:"Something went wrong, please try again later"})}finally{d.classList.add("hidden")}}
//# sourceMappingURL=index.js.map
